# Generated by Django 3.2.22 on 2023-10-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hometask_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodone',
            name='image_file',
            field=models.CharField(default='noimage.png', max_length=100),
        ),
    ]
